version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - errorlint
    - exhaustive
    - gochecknoinits
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unparam
    - unused
    - unconvert

linter-settings:
  gocyclo:
    min-complexity: 15
  govet:
    check-shadowing: true
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
