name: Go

on:
  schedule:
    - cron: "5 */24 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Go Make README.md
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'
        env:
          GIT_NAME: ${{ secrets.GIT_NAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          NASA_BASE_URL: ${{ secrets.NASA_BASE_URL }}
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
      - run: |
          go run ./readme-maker/cmd/cli/
          git config user.name "$GIT_NAME"
          git config user.email "GIT_EMAIL"
          git add README.md
          git commit -m "[bot]: 🤖Update README.md"
          git push origin main
