name: Go

on:
  schedule:
    - cron: "* * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Use Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
        env:
          GIT_NAME: ${{ secrets.GIT_NAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          NASA_BASE_URL: ${{ secrets.NASA_BASE_URL }}
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
      - run: go mod tidy
      - run: go run ./readme-maker/cmd/cli/
      - uses: actions/checkout@v3
      - run: |
          git config user.name "$GIT_NAME"
          git config user.email "GIT_EMAIL"
          git add README.md
          git commit -m "[bot]: 🤖Update README.md"
          git push origin main